### ISSUE TITLE
SpecFlow.Allure 3.5.0.4 - Net Core 5.0 - 'Allure.SpecFlowPlugin.AllureBindingInvoker' threw an exception. -> Couldn't find Allure configuration file

### ISSUE THREAD

**Issue by fescobar** [allure-framework/allure-csharp#168]
Hi guys
I'm creating a new project using NET CORE 5.0
I'm using the latest versions of Specflow that supports `net5.0`. Everything was working fine until I've added `SpecFlow.Allure 3.5.0.4`
Here my dependencies
```sh

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="SpecFlow" Version="3.5.14" />
    <PackageReference Include="SpecFlow.Allure" Version="3.5.0.4" />
    <PackageReference Include="SpecFlow.Tools.MsBuild.Generation" Version="3.5.14" />
    <PackageReference Include="SpecRun.Runner" Version="3.5.8" />
    <PackageReference Include="SpecRun.SpecFlow" Version="3.5.8" />
  </ItemGroup>
```

I have my `allureConfig.json` with `copy always` and also I have my `specflow.json` with the assembly `"assembly": "Allure.SpecFlowPlugin"`
Once I've added `Specflow.Allure` I tried to execute my tests and returns this error:
```sh
The type initializer for 'Allure.SpecFlowPlugin.AllureBindingInvoker' threw an exception. -> Couldn't find Allure configuration file. Please either specify full path to allureConfig.json in the ALLURE_CONFIG environment variable or place allureConfig.json to the 'C:\Users\fescobar\.nuget\packages\allure.commons\3.5.0.4\lib\netstandard2.0' folderSystem.TypeInitializationException: The type initializer for 'Allure.SpecFlowPlugin.AllureBindingInvoker' threw an exception.
 ---> System.IO.FileNotFoundException: Couldn't find Allure configuration file. Please either specify full path to allureConfig.json in the ALLURE_CONFIG environment variable or place allureConfig.json to the 'C:\Users\fescobar\.nuget\packages\allure.commons\3.5.0.4\lib\netstandard2.0' folder
   at Allure.Commons.AllureLifecycle.GetDefaultJsonConfiguration()
   at Allure.Commons.AllureLifecycle..ctor(String jsonConfigurationFile)
   at Allure.Commons.AllureLifecycle.get_Instance()
   at Allure.SpecFlowPlugin.AllureBindingInvoker..cctor()
   --- End of inner exception stack trace ---
```

I've created this small project to reproduce the issue
https://github.com/fescobar/SpecFlow3Net5

If you remove the "SpecFlow.Allure" package and remove the Allure assembly configuration in the  `specflow.json` the project works perfectly.

Thank you in advance.

**Comment by Bakanych** [comment]
hi @fescobar 
Have you tried suggestions that exception text said to you?
`Please either specify full path to allureConfig.json in the ALLURE_CONFIG environment variable or place allureConfig.json to the 'C:\Users\fescobar\.nuget\packages\allure.commons\3.5.0.4\lib\netstandard2.0'`

**Comment by fescobar** [comment]
> hi @fescobar
> Have you tried suggestions that exception text said to you?
> `Please either specify full path to allureConfig.json in the ALLURE_CONFIG environment variable or place allureConfig.json to the 'C:\Users\fescobar\.nuget\packages\allure.commons\3.5.0.4\lib\netstandard2.0'`
Hi @Bakanych 
Yes, already have that configuration in the small project what I've created https://github.com/fescobar/SpecFlow3Net5

https://github.com/fescobar/SpecFlow3Net5/blob/main/allureConfig.json

**Comment by fescobar** [comment]
@Bakanych I've never tried with the env var `ALLURE_CONFIG `. I didn't need it in previous versions, just I need it the file.
With the json directory path in that variable is working.
Thank you.

**Comment by fescobar** [comment]
@Bakanych Sorry, do you have any way to set up the `ALLURE_CONFIG` env var dynamically?. It's asking me for a full path. I would like to set up that with a relative path because I have multiple projects.

**Comment by Bakanych** [comment]
@fescobar It's enough to place allure config to the same directory where plugin is located. I haven't try config with .net 5 yet, but you can check is there Allure.Commons.dll in your test binary folder?

**Comment by fescobar** [comment]
Hi @Bakanych 

I could resolve the problem copying the `allureConfig.json`  where the plugin is located but that doesn't allow me to have different allure configurations for multiple projects on a machine, overall if that machine is for continuous integration. It would be better if that config were taken from the same project as in the previous allure versions.


The file `Allure.Commons.dll` is in my bin directory. You can check the same small project example here:
https://github.com/fescobar/SpecFlow3Net5

```sh
PS C:\Users\fescobar\Documents\git\SpecFlow3Net5\bin\Debug\net5.0> ls


    Directory: C:\Users\fescobar\Documents\git\SpecFlow3Net5\bin\Debug\net5.0


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       09/12/2020     13:08                cs
d-----       09/12/2020     13:08                de
d-----       09/12/2020     13:08                es
d-----       09/12/2020     13:08                fr
d-----       09/12/2020     13:08                it
d-----       09/12/2020     13:08                ja
d-----       09/12/2020     13:08                ko
d-----       09/12/2020     13:08                pl
d-----       09/12/2020     13:08                pt-BR
d-----       09/12/2020     13:08                ref
d-----       09/12/2020     13:08                ru
d-----       09/12/2020     13:08                runtimes
d-----       09/12/2020     13:08                SpecFlowPlusRunner
d-----       09/12/2020     13:08                tr
d-----       09/12/2020     13:08                zh-Hans
d-----       09/12/2020     13:08                zh-Hant
-a----       22/11/2020     04:56          27136 Allure.Commons.dll
-a----       22/11/2020     04:57          27648 Allure.SpecFlowPlugin.dll
-a----       03/12/2020     10:58            907 allureConfig.json
-a----       25/03/2019     13:38          23552 BoDi.dll
-a----       20/11/2020     20:43         168448 CsvHelper.dll
-a----       03/10/2019     11:58         192000 Cucumber.Messages.dll
-a----       09/12/2020     14:47           1753 default.srprofile
-a----       09/02/2018     01:34        2656416 FSharp.Core.dll
-a----       22/11/2018     09:34         166912 Gherkin.dll
-a----       05/03/2019     10:23         332784 Google.Protobuf.dll
-a----       23/02/2017     09:34          58680 Microsoft.TestPlatform.CommunicationUtilities.dll
-a----       23/02/2017     09:34          50448 Microsoft.TestPlatform.CoreUtilities.dll
-a----       23/02/2017     09:34         111904 Microsoft.TestPlatform.CrossPlatEngine.dll
-a----       23/02/2017     09:34          89904 Microsoft.VisualStudio.TestPlatform.Common.dll
-a----       23/02/2017     09:34         125768 Microsoft.VisualStudio.TestPlatform.ObjectModel.dll
-a----       27/06/2019     15:22          70144 MimeTypesMap.dll
-a----       09/11/2019     00:56         693680 Newtonsoft.Json.dll
-a----       14/05/2019     23:37         391168 nunit.framework.dll
-a----       09/12/2020     11:58            136 specflow.json
-a----       11/11/2020     16:43          94208 SpecFlow.Plus.Shared.dll
-a----       09/12/2020     14:47          88506 SpecFlow3Net5.deps.json
-a----       09/12/2020     14:47           8192 SpecFlow3Net5.dll
-a----       09/12/2020     14:47          11732 SpecFlow3Net5.pdb
-a----       09/12/2020     13:08            180 SpecFlow3Net5.runtimeconfig.dev.json
-a----       09/12/2020     13:08            147 SpecFlow3Net5.runtimeconfig.json
-a----       11/11/2020     16:43          15872 SpecRun.Runtime.SpecFlowPlugin.dll
-a----       28/09/2018     21:13          99392 StreamJsonRpc.dll
-a----       15/05/2018     13:29         382096 System.Configuration.ConfigurationManager.dll
-a----       15/05/2018     13:29          25232 System.Security.Cryptography.ProtectedData.dll
-a----       15/05/2018     13:29          96400 System.Security.Permissions.dll
-a----       11/06/2016     23:15         118520 System.Xml.XPath.XmlDocument.dll
-a----       01/12/2020     08:31         314880 TechTalk.SpecFlow.dll
-a----       11/11/2020     16:43          19968 TechTalk.SpecFlow.Plus.RPC.dll
-a----       11/11/2020     16:42          15872 TechTalk.SpecRun.Common.dll
-a----       11/11/2020     16:42          14848 TechTalk.SpecRun.dll
-a----       11/11/2020     16:43         192512 TechTalk.SpecRun.Framework.dll
-a----       11/11/2020     16:43          85504 TechTalk.SpecRun.Framework.Interfaces.dll
-a----       11/11/2020     16:43         121344 TechTalk.SpecRun.Framework.Utils.dll
-a----       11/11/2020     16:44          54784 TechTalk.SpecRun.VisualStudio.TestAdapter.dll
-a----       11/11/2020     16:38            762 TechTalk.SpecRun.VisualStudio.TestAdapter.dll.config
-a----       23/02/2017     09:34          27304 testhost.dll
-a----       30/01/2018     11:51         237568 Utf8Json.dll
```

**Comment by Bakanych** [comment]
Thanks for additional info! I'll check that...

**Comment by DrMarkDunne** [comment]
Experience the same issue as @fescobar, is there an ETA in this? Thanks

**Comment by Bakanych** [comment]
Hi @DrMarkDunne 
It looks like this problem exists with SpecRun only. I've just tried to use both nunit and mstest with Allure and net5 and it works with no issues.
It's pretty hard to maintain all possible combinations of plugins at this time now.
Does using SpecRun essential for you?

**Comment by Bakanych** [comment]
@fescobar @DrMarkDunne 
I've pushed new version: https://www.nuget.org/packages/SpecFlow.Allure/3.5.0.34
It now uses default configuration settings if allureConfig.json file is not found neither in path specified by `ALLURE_CONFIG` env variable nor in binary folder from where ` Allure.Commons.dll` is used.

Please let me know if it fixes your issue.

**Comment by fescobar** [comment]
@Bakanych It's working now. I appreciate too much your effort. I know is difficult to maintain frameworks.
