### ISSUE TITLE
System.AggregateException on running the tests

### ISSUE THREAD

**Issue by swatisharma03** [allure-framework/allure-csharp#19]
Please note that the test works fine. I get this error only if Specflow.allure is installed.

Package: 
    "Allure.Commons" version="2.4.1.1" 
    "CsvHelper" version="7.1.1" 
     "SpecFlow" version="2.4.0" 
     "SpecFlow.Allure" version="2.4.1.1"
    "SpecFlow.xUnit" version="2.4.0" 
     "System.ValueTuple" version="4.5.0" 
    "xunit" version="2.4.0" 

Please find the error details:

Test Name:	Verify the the Powered by  link
Test FullName:	Automation.Framework.Features.LoginPageFeature.VerifyTheThePoweredByLink
Test Source:	C:\Users\swati.sharma\source\repos\Automation.Framework\Automation.Framework\Features\Login.feature : line 5
Test Outcome:	Failed
Test Duration:	0:00:00.001

Result StackTrace:	
----- Inner Stack Trace #1 (System.TypeInitializationException) -----
   at Allure.SpecFlowPlugin.AllureTestTracerWrapper..ctor(ITraceListener traceListener, IStepFormatter stepFormatter, IStepDefinitionSkeletonProvider stepDefinitionSkeletonProvider, SpecFlowConfiguration specFlowConfiguration)
----- Inner Stack Trace -----
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at Allure.Commons.AllureLifecycle..ctor(String jsonConfigurationFile)
   at Allure.Commons.AllureLifecycle..ctor()
   at Allure.Commons.AllureLifecycle.get_Instance()
   at Allure.SpecFlowPlugin.AllureTestTracerWrapper..cctor()
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
Result Message:	
System.AggregateException : One or more errors occurred.
---- System.TypeInitializationException : The type initializer for 'Allure.SpecFlowPlugin.AllureTestTracerWrapper' threw an exception.
-------- System.IO.FileNotFoundException : Could not find file 'C:\Users\swati.sharma\AppData\Local\Temp\61766ac7-10ce-4e46-9566-141538edfcc9\61766ac7-10ce-4e46-9566-141538edfcc9\assembly\dl3\25915518\007786f7_d54fd401\allureConfig.json'.
---- The following constructor parameters did not have matching fixture data: FixtureData fixtureData

**Comment by Ukrainis** [comment]
To correctly run Specflow scenarios with Allure, you need to have allureConfig.json file in your bin folder (where project is built). You can do it manually every time, of make Visual Studio to do it for you by setting in properties for allureConfig.json:
<img width="727" alt="allure" src="https://user-images.githubusercontent.com/11504404/46616147-91c91080-cb22-11e8-9cc7-f5a77b940647.png">

**Comment by swatisharma03** [comment]
![image](https://user-images.githubusercontent.com/19341405/46617500-cc2bb100-cb14-11e8-90c0-888d424f3545.png)

I have done that. But still getting the same error.

**Comment by Ukrainis** [comment]
Please, try to put file manually and verify.
Can't tell, why it is watching temporary folder. And what is your project location?
Maybe you can push this solution to GitHub for people to investigate your problem?

**Comment by swatisharma03** [comment]
The issue is now resolved. 
A couple of things :
- There were two unitTestProvider in appconfig, one for xunit and another for specflow . Now it only has 
    <unitTestProvider name="SpecRun" />.
- Cleared the Temp folder and restarted visual studio.
