### ISSUE TITLE
Exception: Cannot access a disposed object

### ISSUE THREAD

**Issue by NikitaEgorov** [allure-framework/allure-csharp#500]
Hi everyone, I'm sorry that I can't give you the details, but I've already spent 8 hours trying to get at least some details and all without success.

After updating to version 2.12.0, these errors began to appear randomly when debugging tests. And I don't understand the reason for their occurrence at all.
```c#
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Threading.ThreadLocal`1[[System.Collections.Concurrent.ConcurrentBag`1+WorkStealingQueue[[MonoMod.Core.Platforms.Memory.PagedMemoryAllocator+Page, 0Harmony, Version=2.3.3.0, Culture=neutral, PublicKeyToken=null]], System.Collections.Concurrent, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at System.Collections.Concurrent.ConcurrentBag`1.Add(T item)
   at MonoMod.Core.Platforms.Memory.PagedMemoryAllocator.RegisterForCleanup(Page page) in /_/src/MonoMod.Core/Platforms/Memory/PagedMemoryAllocator.cs:line 375
   at MonoMod.Core.Platforms.Memory.PagedMemoryAllocator.Page.FreeMem(UInt32 offset, UInt32 size) in /_/src/MonoMod.Core/Platforms/Memory/PagedMemoryAllocator.cs:line 240
   at MonoMod.Core.Platforms.Memory.PagedMemoryAllocator.PageAllocation.Dispose(Boolean disposing) in /_/src/MonoMod.Core/Platforms/Memory/PagedMemoryAllocator.cs:line 56
   at MonoMod.Core.Platforms.Memory.PagedMemoryAllocator.PageAllocation.Finalize() in /_/src/MonoMod.Core/Platforms/Memory/PagedMemoryAllocator.cs:line 66
```

When I roll back to 2.11, everything becomes normal

**Comment by saragulov** [comment]
Hi, I have the same problem. Are there any updates on this issue? Maybe there are some workarounds?

**Comment by sphinxy** [comment]
For me it works manually adding https://www.nuget.org/packages/Lib.Harmony/2.3.5 to same project where Allure.XUnit 2.12.0 is added

**Comment by NikitaEgorov** [comment]
@sphinxy tnx
I'll check it out. 
And I'll try to push a new version of Harmony to the Allure repository.
